<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [ ]:
import pandas as pd
import numpy as np
import pandas as pd

%matplotlib inline

### 1. Explore Data

Perform EDA on this dataset. Find Dependent and Independent Variables to predict house price.

In [9]:
# Read CSV
house_csv = pd.read_csv("Sacramento_transactions.csv")
house_csv.head()

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

### 2. Predict Price

We are going to predict `price` from available information.

#### 2.1 What is the Target Variable? Why?

In [10]:
# ANSWER

#The target variable is price because we are trying to find out the prices in of houses in the area.

#### 2.2 List all possible variables which might be Independent/Predictor variable.

In [11]:
# ANSWER
#Independent variables = Street, number of beds, number of baths

#### 2.3 Find correlation between variables

Find correlation between variables. Which is the best predictor? Why? State your reason.

In [12]:
# ANSWER
house_csv.corr()
# the correlation between price and number of beds and number of baths 


zip      beds     baths    sq__ft     price  latitude  \
zip        1.000000  0.125319  0.069165  0.130108 -0.093353 -0.290389   
beds       0.125319  1.000000  0.839650  0.684041  0.342024 -0.291307   
baths      0.069165  0.839650  1.000000  0.665690  0.416208 -0.235792   
sq__ft     0.130108  0.684041  0.665690  1.000000  0.333897 -0.383274   
price     -0.093353  0.342024  0.416208  0.333897  1.000000 -0.039573   
latitude  -0.290389 -0.291307 -0.235792 -0.383274 -0.039573  1.000000   
longitude -0.539904 -0.053993  0.016582 -0.177742  0.284485  0.387925   

           longitude  
zip        -0.539904  
beds       -0.053993  
baths       0.016582  
sq__ft     -0.177742  
price       0.284485  
latitude    0.387925  
longitude   1.000000

#### 2.4 Find Coefficient and Intercept using Linear Regression

Using LinearRegression of sklearn.linear_model package find Coefficient and Intercept.

Create an instance of LinearRegression.

Explore following methods:

- fit
- predict
- score

In [13]:
from sklearn.linear_model import LinearRegression

##### 2.4.1 Fit predictor and target variables using linear regression 

In [14]:
# ANSWER

X = house_csv['sq__ft'].values.reshape(-1,1) #when call fit function on linear regression, thex expects a dataframe and it has to be 2 dimensional. it reshapes the columns/panda series to a 2d dataframe. the -1 is to tell the function to infer the value. like saying, idk how many rows but i know i want 1 column. and the 1 is the width of the rows. reshape it to (985,1) array
Y = house_csv['price']




In [18]:
house_csv['sq__ft']

0       836
1      1167
2       796
3       852
4       797
       ... 
980    2280
981    1477
982    1216
983    1685
984    1362
Name: sq__ft, Length: 985, dtype: int64

In [20]:
house_csv['sq__ft'].values

array([ 836, 1167,  796,  852,  797, 1122, 1104, 1177,  941, 1146,  909,
       1289,  871, 1020, 1022, 1134,  844,  795,  588, 1356, 1118, 1329,
       1240, 1601,  901, 1088,  963, 1119, 1380, 1248, 1039, 1152, 1380,
       1116, 1039, 1418, 1082, 1472, 1146,  760, 1304, 1207, 1056, 1043,
       1587, 1120, 1580, 1955, 1656, 1477, 1188, 1590, 1463, 1714, 1185,
       1406, 1943, 1172, 1152, 1851, 1215, 1130, 1603, 1479, 1420, 1280,
       1586, 1362, 2162, 1266, 1715, 1820,  936,    0, 1511, 1590, 1596,
       1341, 2136, 1616, 1478, 1287, 1277, 1448, 2235, 2093, 1193, 2163,
       1269,    0,  958, 2508, 1305, 1591, 1326, 1843, 1921, 2790, 1541,
       1018,    0, 1672, 1380,  975, 2372, 1446, 1284, 3009, 3612, 2056,
       1993, 1857, 1126, 2213, 2494, 1843, 1520, 2800, 2309, 2367, 3516,
          0, 1914, 1690, 2725, 2354,    0, 2185, 1801, 1961, 3134, 1915,
          0,    0, 2734, 2110, 3164, 3599, 2054, 1830, 1627, 3440, 2846,
       2359, 2052, 3433, 3615,    0, 2687, 2724, 34

In [21]:
x = house_csv[['sq__ft']]
type(house_csv[['sq__ft']])

pandas.core.frame.DataFrame

In [22]:
lm =LinearRegression(n_jobs=1) #n_jobs to make the processing faster. linearRegression here is a blank model and we put the inputs in later. its a generic model but there are other types of linearregression. the capitalisation in linearregression indicates whether we are working with a model object. 
lm.fit(X,Y)

LinearRegression(n_jobs=1)

##### 2.4.2 Find R Score

Find $R^2$ Using ```score``` method of Linear Regression.

In [23]:
# ANSWER
from sklearn.metrics import r2_score
lm.score(X,Y)

0.11148717682951437

In [24]:
y_pred = lm.predict(X)
r2_score(Y,y_pred)

0.11148717682951437

### 3. Splitting Data

In [25]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Using `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [26]:
# ANSWER
## Create training and testing subsets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=42)

#### 3.2 Check Shape, Sample of Test Train Data

In [27]:
# ANSWER
## Check training/test data
X.shape

(985, 1)

#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [28]:
# ANSWER
lm.fit(X_train,y_train)

LinearRegression(n_jobs=1)

In [29]:
# ANSWER
r_sq = lm.score(X_test,y_test) #output is r square which measures that 13% of increase in square feet can be attributed to the increase in price.

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using linear regression model.**

In [35]:
# ANSWER
lm.coef_,lm.intercept_

(array([47.43508406]), 166482.34144968857)

In [36]:
z= 47.43508406
p= 166482.34144968857
predicted_price = z * 1204 + p
predicted_price

223594.18265792856

#### Find the error

In [33]:
# Predict price from X_test
y_pred = lm.predict(X_test) # i am doing this to pass X into the model to get the response
y_pred

array([209458.52761247, 279472.71169224, 259549.97638499, 248971.95263852,
       238915.71481676, 166482.34144969, 166482.34144969, 256609.00117297,
       166482.34144969, 166482.34144969, 217807.10240789, 166482.34144969,
       220558.33728366, 166482.34144969, 219040.41459358, 241714.38477659,
       204193.23328127, 204240.66836534, 166482.34144969, 309214.50940092,
       253288.54528842, 231088.92594606, 277195.82765713, 226487.72279177,
       222171.13014186, 243516.91797106, 258506.40453556, 218660.93392106,
       242188.73561724, 253668.02596094, 226677.46312803, 254284.68205379,
       237872.14296734, 238678.53939644, 166482.34144969, 222171.13014186,
       206138.07172793, 242425.91103757, 215767.3937931 , 166482.34144969,
       262775.5621014 , 195417.74272927, 166482.34144969, 275915.08038737,
       254284.68205379, 243706.65830732, 233365.80998117, 287441.80581514,
       227388.989389  , 367891.70838918, 235595.25893222, 225681.32636266,
       239674.6761618 , 2



---



---



> > > > > > > > > © 2021 Institute of Data


---



---



